package com.aurum.top20next;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

public final class EnrichedMainActivity extends Activity {
  private static final int NAVY=Color.rgb(2,8,20),CARD=Color.rgb(8,25,48),GOLD=Color.rgb(212,175,55),TEXT=Color.rgb(239,244,252),MUTED=Color.rgb(157,174,196),RED=Color.rgb(240,96,96),GREEN=Color.rgb(89,204,144);
  private final ExecutorService pool=Executors.newSingleThreadExecutor(); private LinearLayout body; private TextView status; private SharedPreferences prefs; private JSONObject data;
  public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("aurum",MODE_PRIVATE);loadCache();draw();String u=prefs.getString("endpoint","");if(u.startsWith("https://"))refresh(u);}
  private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} private TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(0,dp(3),0,dp(3));return v;}
  private LinearLayout card(String h){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(13),dp(15),dp(13));c.setBackgroundColor(CARD);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));c.setLayoutParams(p);TextView x=t(h,18,TEXT);x.setTypeface(Typeface.DEFAULT_BOLD);c.addView(x);body.addView(c);return c;}
  private void row(LinearLayout c,String k,String v){LinearLayout r=new LinearLayout(this);r.setPadding(0,dp(5),0,dp(5));TextView a=t(k,13,MUTED),b=t(v,13,TEXT);b.setGravity(Gravity.END);b.setTypeface(Typeface.DEFAULT_BOLD);r.addView(a,new LinearLayout.LayoutParams(0,-2,1));r.addView(b,new LinearLayout.LayoutParams(0,-2,1));c.addView(r);}
  private void draw(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);LinearLayout top=new LinearLayout(this);top.setPadding(dp(16),dp(14),dp(16),dp(10));top.setGravity(Gravity.CENTER_VERTICAL);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.ic_launcher);top.addView(logo,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.VERTICAL);n.setPadding(dp(12),0,0,0);TextView brand=t("AURUM TOP20 PRO X",20,GOLD);brand.setTypeface(Typeface.DEFAULT_BOLD);n.addView(brand);n.addView(t("Zenginleştirilmiş S",25,TEXT));top.addView(n,new LinearLayout.LayoutParams(0,-2,1));status=t(data==null?"VERİ YOK":"ÖNBELLEK",12,data==null?GOLD:MUTED);status.setTypeface(Typeface.DEFAULT_BOLD);top.addView(status);root.addView(top);ScrollView s=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(4),dp(14),dp(40));s.addView(body);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);render();}
  private String d(Object x){if(x==null||x==JSONObject.NULL||String.valueOf(x).trim().isEmpty())return "—";return String.valueOf(x);} private String pct(Object x){String s=d(x);if(s.equals("—"))return s;try{return String.format(Locale.US,"%.2f%%",Double.parseDouble(s.replace(',','.')));}catch(Exception e){return s;}}
  private void render(){body.removeAllViews();LinearLayout con=card("Bağlantı");EditText e=new EditText(this);e.setText(prefs.getString("endpoint",""));e.setHint("Apps Script /exec adresi");e.setTextColor(TEXT);e.setHintTextColor(MUTED);con.addView(e);Button b=new Button(this);b.setText("Kaydet ve Yenile");b.setOnClickListener(v->{String u=e.getText().toString().trim();prefs.edit().putString("endpoint",u).apply();refresh(u);});con.addView(b);if(data==null){card("Durum").addView(t("Endpoint tanımlanınca S, K1–K5, kalite, performans ve İş Yatırım şirket kartı metrikleri gösterilir. Veri uydurulmaz.",14,MUTED));return;}JSONArray a=data.optJSONArray("selection");LinearLayout sum=card("Özet");row(sum,"API",data.optString("apiVersion","—"));row(sum,"S adayı",a==null?"0":String.valueOf(a.length()));JSONObject en=data.optJSONObject("enrichment");row(sum,"Zenginleştirme",en==null?"—":en.optString("version","—"));if(a==null)return;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String sym=o.optString("symbol","?");LinearLayout c=card((i+1)+" · "+sym);row(c,"S skoru",d(o.opt("score")));row(c,"Giriş",d(o.opt("entryPrice")));JSONObject x=o.optJSONObject("enrichment");if(x==null){row(c,"Şirket kartı","VERİ YOK");continue;}row(c,"Öneri",d(x.opt("recommendation")));row(c,"Öneri tarihi",d(x.opt("recommendationDate")));row(c,"Hedef fiyat",d(x.opt("targetPrice")));row(c,"Hedef potansiyeli",pct(x.opt("targetPotentialPct")));row(c,"Hedef revizyonu",pct(x.opt("targetRevisionPct")));row(c,"F/K",d(x.opt("pe")));row(c,"PD/DD",d(x.opt("pb")));row(c,"ROE",pct(x.opt("roePct")));row(c,"Yabancı oranı",pct(x.opt("foreignOwnershipPct")));row(c,"Yabancı akım etkisi",pct(x.opt("foreignFlowImpactPct")));row(c,"3A hacim mn$",d(x.opt("avgVolume3MMnUsd")));row(c,"Temettü verimi",pct(x.opt("dividendYieldPct")));row(c,"Göreceli 1G",pct(x.opt("relative1dPct")));row(c,"Göreceli 1H",pct(x.opt("relative1wPct")));row(c,"Göreceli 1A",pct(x.opt("relative1mPct")));row(c,"Kapsam",pct(x.optDouble("coverage",0)*100));row(c,"Çapraz doğrulama",x.optBoolean("crossValid")?"UYUMLU":"UYARI");JSONArray w=x.optJSONArray("crossWarnings");if(w!=null&&w.length()>0)c.addView(t("Uyarılar: "+w.toString(),12,RED));}}
  private void refresh(String u){if(!u.startsWith("https://")){Toast.makeText(this,"Geçerli HTTPS endpoint girin",Toast.LENGTH_LONG).show();return;}status.setText("BAĞLANIYOR");pool.submit(()->{try{URL url=new URL(u+(u.contains("?")?"&":"?")+"action=mobileSnapshot");HttpURLConnection h=(HttpURLConnection)url.openConnection();h.setConnectTimeout(15000);h.setReadTimeout(30000);int code=h.getResponseCode();InputStream in=code>=400?h.getErrorStream():h.getInputStream();StringBuilder sb=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null)sb.append(line);}if(code<200||code>=300)throw new IOException("HTTP "+code);JSONObject j=new JSONObject(sb.toString());if(!j.optBoolean("ok",false))throw new IOException(j.optString("message",j.optString("error","API_ERROR")));prefs.edit().putString("cache",j.toString()).apply();runOnUiThread(()->{data=j;status.setText("VERİ HAZIR");render();});}catch(Exception ex){runOnUiThread(()->{status.setText("HATA");Toast.makeText(this,ex.getMessage(),Toast.LENGTH_LONG).show();});}});}
  private void loadCache(){try{String c=prefs.getString("cache","");if(!c.isEmpty())data=new JSONObject(c);}catch(Exception ignored){}}
  protected void onDestroy(){pool.shutdownNow();super.onDestroy();}
}
