package com.aurum.top20next;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.text.*;import java.util.*;import java.util.concurrent.*;

public final class RepositoryMainActivity extends Activity {
  private static final String DATA_URL="https://raw.githubusercontent.com/netadalet-oss/bist-ai-top20/mobile/aurum-top20-pro-x/data/latest.json";
  private static final int NAVY=Color.rgb(2,8,20),CARD=Color.rgb(8,25,48),GOLD=Color.rgb(212,175,55),TEXT=Color.rgb(239,244,252),MUTED=Color.rgb(157,174,196),RED=Color.rgb(240,96,96),GREEN=Color.rgb(89,204,144);
  private final ExecutorService pool=Executors.newSingleThreadExecutor(); private SharedPreferences prefs; private JSONObject data; private LinearLayout body; private TextView status;
  @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("aurum_repo",MODE_PRIVATE);loadCache();draw();refresh(false);}
  private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} private TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(0,dp(3),0,dp(3));return v;}
  private LinearLayout card(String h){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(13),dp(15),dp(13));c.setBackgroundColor(CARD);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));c.setLayoutParams(p);TextView x=t(h,18,TEXT);x.setTypeface(Typeface.DEFAULT_BOLD);c.addView(x);body.addView(c);return c;}
  private void row(LinearLayout c,String k,String v){LinearLayout r=new LinearLayout(this);r.setPadding(0,dp(5),0,dp(5));TextView a=t(k,13,MUTED),b=t(v,13,TEXT);b.setGravity(Gravity.END);b.setTypeface(Typeface.DEFAULT_BOLD);r.addView(a,new LinearLayout.LayoutParams(0,-2,1));r.addView(b,new LinearLayout.LayoutParams(0,-2,1));c.addView(r);}
  private String d(Object x){if(x==null||x==JSONObject.NULL||String.valueOf(x).trim().isEmpty())return "—";return String.valueOf(x);} private String pct(Object x){String s=d(x);if(s.equals("—"))return s;try{return String.format(Locale.US,"%.2f%%",Double.parseDouble(s.replace(',','.')));}catch(Exception e){return s;}}
  private void draw(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);LinearLayout top=new LinearLayout(this);top.setPadding(dp(16),dp(14),dp(16),dp(10));top.setGravity(Gravity.CENTER_VERTICAL);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.ic_launcher);top.addView(logo,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.VERTICAL);n.setPadding(dp(12),0,0,0);TextView brand=t("AURUM TOP20 PRO X",20,GOLD);brand.setTypeface(Typeface.DEFAULT_BOLD);n.addView(brand);n.addView(t("API → GitHub → Telefon",23,TEXT));top.addView(n,new LinearLayout.LayoutParams(0,-2,1));status=t(data==null?"VERİ YOK":"ÖNBELLEK",12,data==null?GOLD:MUTED);status.setTypeface(Typeface.DEFAULT_BOLD);top.addView(status);root.addView(top);ScrollView s=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(4),dp(14),dp(40));s.addView(body);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);render();}
  private void render(){body.removeAllViews();LinearLayout sync=card("Depo Senkronizasyonu");row(sync,"Kaynak","GitHub data/latest.json");row(sync,"Harici kaynaklar","ISYATIRIM → ISYATIRIM_LIVE → YAHOO → YAHOO_QUOTE → BIGPARA → STOOQ");Button b=new Button(this);b.setText("ŞİMDİ YENİLE");b.setOnClickListener(v->refresh(true));sync.addView(b);if(data==null){card("Durum").addView(t("Depo verisi henüz indirilemedi. Uygulama Google Drive veya Apps Script kullanmaz.",14,MUTED));return;}row(sync,"Üretim zamanı",data.optString("generatedAt","—"));row(sync,"Evren",String.valueOf(data.optInt("universeSize",0)));row(sync,"Yöntem",data.optString("method","—"));JSONArray top=data.optJSONArray("top20");if(top==null||top.length()==0){card("Top 20").addView(t(data.optString("status","Depo güncelleme işi henüz veri üretmedi."),14,MUTED));return;}for(int i=0;i<top.length();i++){JSONObject o=top.optJSONObject(i);if(o==null)continue;LinearLayout c=card(o.optInt("rank",i+1)+" · "+o.optString("symbol","?"));row(c,"Skor",d(o.opt("score")));row(c,"Fiyat",d(o.opt("price")));row(c,"Günlük",pct(o.opt("changePct")));row(c,"5 gün",pct(o.opt("return5dPct")));row(c,"20 gün",pct(o.opt("return20dPct")));row(c,"Çapraz doğrulama",o.optBoolean("crossValid")?"UYUMLU":"UYARI");JSONObject lin=o.optJSONObject("lineage");if(lin!=null)row(c,"Fiyat kaynağı",lin.optString("price","—"));}}
  private void refresh(boolean manual){status.setText("YENİLENİYOR");pool.submit(()->{try{URL url=new URL(DATA_URL+"?t="+System.currentTimeMillis());HttpURLConnection h=(HttpURLConnection)url.openConnection();h.setConnectTimeout(15000);h.setReadTimeout(30000);h.setRequestProperty("Accept","application/json");int code=h.getResponseCode();if(code<200||code>=300)throw new IOException("HTTP "+code);StringBuilder sb=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(h.getInputStream(),StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null)sb.append(line);}JSONObject j=new JSONObject(sb.toString());prefs.edit().putString("cache",j.toString()).putLong("cacheTs",System.currentTimeMillis()).apply();runOnUiThread(()->{data=j;status.setText(j.optBoolean("ok",false)?"GÜNCEL":"BEKLEMEDE");render();if(manual)Toast.makeText(this,"Depo verisi yenilendi",Toast.LENGTH_SHORT).show();});}catch(Exception ex){runOnUiThread(()->{status.setText(data==null?"HATA":"ÖNBELLEK");if(manual)Toast.makeText(this,"Yenileme hatası: "+ex.getMessage(),Toast.LENGTH_LONG).show();});}});}
  private void loadCache(){try{String c=prefs.getString("cache","");if(!c.isEmpty())data=new JSONObject(c);}catch(Exception ignored){}}
  @Override protected void onDestroy(){pool.shutdownNow();super.onDestroy();}
}
